### ISSUE TITLE
colored police in the  declension tables (regression)

### ISSUE THREAD

**Issue by MartineMK35** [digitalpalireader/digitalpalireader#106]
see screen shoot
![loss of coloring and title](https://user-images.githubusercontent.com/61345779/75089489-a06a6900-5559-11ea-8159-c354b94028a8.PNG)
![loss of coloring](https://user-images.githubusercontent.com/61345779/75089490-a3fdf000-5559-11ea-9906-d5bac5671d3f.PNG)

**Comment by vasiltabakov** [comment]
I've just checked out the latest master and without doing anything I see the highlights. In fact I've tested with the very same word, here's a screenshot:
![image](https://user-images.githubusercontent.com/1178309/76513149-82a86980-645e-11ea-9067-1e62088b196a.png)

I guess this self-resolved with some of the refactoring changes since it was reported.
I think this can be closed now.

**Comment by sumbodhi** [comment]
I've just checked out the latest master and without doing anything I see the highlights. In fact I've tested with the very same word, here's a screenshot:
![image](https://user-images.githubusercontent.com/1178309/76513149-82a86980-645e-11ea-9067-1e62088b196a.png)

I guess this self-resolved with some of the refactoring changes since it was reported.
I think this can be closed now.
