### ISSUE TITLE
Regex malfucntion in PES dictionary

### ISSUE THREAD

**Issue by bdhrs** [digitalpalireader/digitalpalireader#284]
When searching with regex in PTS dictionary, the results are irregular. Here's an example. 

- Searching for dhā\b should give all words **_ending_** in dhā
- but search results contain all words **_containing_** dhāl 
- search with dhā$ works correctly

Any ideas why this happens?

![regex in pts](https://user-images.githubusercontent.com/64521731/98794774-716d8d80-242f-11eb-9a70-b36a93ffb1dd.gif)

**Comment by dangeol** [comment]
Further below I post a link to an explanation why word boundaries work only with members of the `\w` character class, meaning that `\b` in conjunction with special chars such as ā don't work because the location between the special char and a regular char will be considered a word boundary. This explains why dhā\b search results contain all words containing dhā.
[https://stackoverflow.com/questions/2449779/why-cant-i-use-accented-characters-next-to-a-word-boundary/2449892#2449892](https://stackoverflow.com/questions/2449779/why-cant-i-use-accented-characters-next-to-a-word-boundary/2449892#2449892)

In my opinion the search results are as expected. Please use `$` in the case of your example.

**Comment by bdhrs** [comment]
ah thank you for that! explains much of the weirdness that i have experienced working with pāli and with my limited knowledge of regex. side note. how to include all pāli unicode characters in a set? for example [a-z]?

**Comment by dangeol** [comment]
@bdhrs as already discussed, a workaround is using `[āīūṭḍṅṇṃṃñḷ]`, and after some investigations, I couldn't come up yet with something elegant similar to `[a-z]`.

@parthopdas if you agree, we might close this issue.

**Comment by parthopdas** [comment]
hi @dangeol - i am fine with closing it unless v @bdhrs has any other suggestions.
