### ISSUE TITLE
GDPR stuff

### ISSUE THREAD

**Issue by parthopdas** [digitalpalireader/digitalpalireader#54]
@cesiumetta please use this text. I will work with @christopherdolan to get you the link to sirimangalo policy.

> Digital Pāli Reader uses cookies and similar technologies on our website and platform to operate and our services, customize your experience with our services, test new changes and features, help us understand how you use our services. You can read more about this in our Cookie Policy.
> OK, hide this

![image](https://user-images.githubusercontent.com/2140460/80965644-3f62e980-8e56-11ea-946c-6248d8e4185b.png)

**Comment by parthopdas** [comment]
resolved as per conversation with chris
![image](https://user-images.githubusercontent.com/2140460/75776095-0b5c4100-5d9f-11ea-96b4-2defd09bf33e.png)

**Comment by parthopdas** [comment]
Need to obtain consent. Need to speak to Chris for additional info.

**Comment by parthopdas** [comment]
@christopherdolan can you please provide a link to our privacy policy. @cesiumetta is working on this - see above for a mock.

**Comment by christopherdolan** [comment]
Here is the privacy policy which we've evolved as Sirimangalo services have continued to incorporate more and more third-party plugins and all. Hopefully it suffices for your needs, but please let me know if it has to change again, due to additional services gaining access to user information. https://www.sirimangalo.org/info/our-privacy-policy/
